apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudl-server
    spec:
      containers:
        - name: cloudl-server
          image: kavinduchamiran/cloudl-server:latest
          ports:
            - containerPort: 5000
              name: nodejs-port
  selector:
    matchLabels:
      app: cloudl-server

---
apiVersion: v1
kind: Service
metadata:
  name: cloudl-server-service
spec:
  selector:
    app: cloudl-server
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: LoadBalancer